packages:
  - "apps/*"
  - "packages/*"
catalog:
  next: "15.5.7"
  react: "^19.1.0"
  react-dom: "^19.1.0"
  typescript: "5.9.3"
  eslint: "^9.34.0"
  "@types/react": "19.1.0"
  "@types/react-dom": "19.1.1"
  "@types/node": "^22.15.3"
  "@emotion/react": "^11.13.5"
  "@emotion/styled": "^11.13.5"
  lottie-react: "^2.4.1"
  notion-client: "^7.7.1"
  notion-types: "^7.7.1"
  "@notionhq/client": "^2.2.15"
  react-notion-x: "^7.7.1"
