packages:
  - "apps/*"
  - "packages/*"
catalog:
  next: "15.5.7"
  react: "^19.1.0"
  react-dom: "^19.1.0"
  typescript: "5.9.3"
  eslint: "^9.34.0"
  "@types/react": "19.1.0"
  "@types/react-dom": "19.1.1"
  "@types/node": "^22.15.3"
  "@emotion/react": "^11.13.5"
  "@emotion/styled": "^11.13.5"
  "@emotion/cache": "^11.14.0"
  notion-client: "^7.7.1"
  notion-types: "^7.7.1"
  "@notionhq/client": "^2.2.15"
  react-notion-x: "^7.7.1"
  matter-js: "^0.20.0"
  "@types/matter-js": "^0.20.2"
  poly-decomp: "^0.3.0"
  "@svgr/webpack": "^8.1.0"
  dotenv: "^16.4.5"
  clsx: "^2.1.1"
  tailwind-merge: "^2.5.4"
  prettier: "^3.7.4"
  turbo: "^2.6.3"
  "@vercel/analytics": "^1.6.1"
